; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.15
	adafruit/Adafruit CAP1188 Library@^1.1.3
	adafruit/Adafruit GFX Library@^1.12.4
	arduino-libraries/Arduino_LSM6DS3@^1.0.3
	sparkfun/SparkFun LSM6DS3 Breakout@^1.0.3
	adafruit/Adafruit VEML7700 Library@^2.1.6
	adafruit/Adafruit NeoPixel
	olikraus/U8g2@^2.36.15
monitor_dtr = 0
monitor_rts = 0
